### ISSUE TITLE
specifying -y DATA produces crash

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/shadeMS#35]
Not surprisingly. But better to catch it up front, and ask for a complex component to be specified.

```
tab.getcoldesc("DATA")['valueType'] == 'complex' 
```

...is an easy check for complex-valued columns.

**Comment by sjperkins** [comment]
np.iscomplexobj on the dataframe DATA array is another potential location to perform the check.

**Comment by o-smirnov** [comment]
I was going to check up front before the train is set in motion, but on the other hand, if we're going to fall back to ``amp`` by default, that's as good as place as any...

**Comment by sjperkins** [comment]
> I was going to check up front before the train is set in motion, but on the other hand, if we're going to fall back to `amp` by default, that's as good as place as any...

The train is only set in motion once a dask.compute() happens within the program.

An xds_from_ms call is a relatively lightweight inspection of the table to obtain it's metadata and structure. Thus, the resulting datasets are still lazy. However, there's still a lot of info on the dataset that should remove the need to directly inspect the table. If you still wish to interact with the table object, one can obtain the TableProxy associated with the dataset by calling 

```python
datasets, table_proxy = xds_from_ms(ms, table_proxy=True)
data = table_proxy.getcol("DATA").result()
```

Note the table_proxy methods return Futures because its submitting the calls on a single thread ThreadPoolExecutor. Further information is here https://dask-ms.readthedocs.io/en/latest/api.html#tableproxies
