### ISSUE TITLE
Continuous data colourised by discrete map in bins

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/shadeMS#40]
```
shadems -x BASELINE -y FREQ --colour-by CORRECTED_DATA:amp:XX --field 0 1587194692_sdp_l0_wtspec.ms
```

![plot-1587194692_sdp_l0_wtspec-J0408-6545-FREQ-BASELINE-CORRECTED_DATA-amp](https://user-images.githubusercontent.com/6533799/80287878-ed221a00-872b-11ea-86a0-1788a61dcc05.png)

Trying to circumvent this with `--dmap`:

```
shadems --dmap bkr -x BASELINE -y FREQ --colour-by CORRECTED_DATA:amp:XX --field 0 --iter-scan 1587194692_sdp_l0_wtspec.ms
```

![plot-1587194692_sdp_l0_wtspec-J0408-6545-scan_1-FREQ-BASELINE-CORRECTED_DATA-amp](https://user-images.githubusercontent.com/6533799/80287896-05923480-872c-11ea-9363-396d4c0eb229.png)

and:

```
shadems --cnum 512 --dmap bkr -x BASELINE -y FREQ --colour-by CORRECTED_DATA:amp:XX --field 0 --iter-scan 1587194692_sdp_l0_wtspec.ms
```

![plot-1587194692_sdp_l0_wtspec-J0408-6545-scan_1-FREQ-BASELINE-CORRECTED_DATA-amp](https://user-images.githubusercontent.com/6533799/80287983-a84ab300-872c-11ea-89ec-cb520dcca1b9.png)

**Comment by o-smirnov** [comment]
Yeah that was a logic bug compounded by misleading help strings I think. Anyway to clarify:

* ``--colour-by`` has two modes, for discrete and continuous values.

* In continuous mode, ``--cmin`` and ``--cmax`` **must** be specified (the logic error was in not throwing an error, which led subsequent code to collapse back into discrete mode, and plot god knows what actually)

* You can tell it's in continuous mode by the colorbar tickmarks. In discrete mode every color bin has a label. In continuous mode it looks like an axis. (Also, in discrete mode the plot title can mention "modulo", in continuous mode it would never):

![image](https://user-images.githubusercontent.com/6470079/80306420-76d0f680-87c3-11ea-8c16-cb9d388cb139.png)

* ``--cnum`` is optional. In discrete mode, it determines the max number of discrete colours. If the column takes on more values than ``--cnum``, the modulo thing kicks in. If the column takes on fewer values, the lesser number is used.

* In continuous mode, ``--cnum`` determines how many bins to discretize the continuous value into (there are 16 in the plot above).

* The colour map used is ``--bmap`` for continuous axes and ``--dmap`` for discrete ones. The ``--cmap`` map is used for "monochrome" plots. 

* Your all-blue plot came about because you forced the "bkr" map onto a discrete-mode plot (which should not have been in discrete mode, but see logic bug above). Since discrete mode just picks the first few (say, 16, or 64) colours from the map, it doesn't come out looking well with colourmaps designed for continuous data.

**Comment by IanHeywood** [comment]
Gotcha, thanks.

And we can't have it offer defaults for `cmin` and `cmax` without essentially running the whole thing twice, right?

**Comment by o-smirnov** [comment]
Yeah... but let me look again what datashader does, because it already runs the thing twice for X/Y axis limits... the sensible thing would be to look up cmin/cmax at the same time.

I'd also like to get colour-by-std working (https://github.com/holoviz/datashader/issues/900). But if your value is not zero-mean, getting the std out also needs two pases.

**Comment by o-smirnov** [comment]
Hmmm, as the assassin said, hang on, maybe I can pull this job off for 5000...

**Comment by o-smirnov** [comment]
Yep, the old one-bullet trick worked. Proved to be low-hanging fruit, these!

Is this really the plot you're looking for though? I'm trying to understand if there's a bug, or if I just don't understand what I'm seeing:

![image](https://user-images.githubusercontent.com/6470079/80316103-2924b000-87fc-11ea-8a5b-97b233e45717.png)

Try the ``auto-bounds`` branch please.

**Comment by IanHeywood** [comment]
Thanks. It's not the plot _I'm_ looking for, but it's not for me to say what plots users want to look at! I don't really get what I'm seeing here either. I guess it's weird because the baseline index won't necessarily be ordered in any meaningful way. Frequency vs baseline length would probably be more informative or intuitive, but probably only if we have a u,v-distance-in-metres option instead of the default wavelengths.

**Comment by o-smirnov** [comment]
Well I'm trying to figure out if it's being plotted incorrectly, or I just don't understand the implications of what I'm seeing... the spectrum for antennas 0:8 looks like this.

![image](https://user-images.githubusercontent.com/6470079/80320131-d277a000-8814-11ea-8c8a-3612c2a8ea36.png)

So I don't understand all the blue in the colour by amplitude plot above.

**Comment by IanHeywood** [comment]
If the frequency vs baseline plot is a single correlation then each point on it will represent many times. How does it handle each point being many times when colourising by amplitude? Will it be all the colours of the many time slots alpha'd on top of each other? Maybe this plot is more likely to be visually skewed by small numbers of anomalously high or low values.

The red points are all in the hot RFI zones in frequency.

**Comment by o-smirnov** [comment]
I've convinced myself that it's wrong, and I have some debugging to do tomorrow.

> Will it be all the colours of the many time slots alpha'd on top of each other?

Pretty much. More precisely, it should count the number of points in each colour bin, then mix the colours, weighted by their representation. So if a spot on the canvas has amplitudes all over the place, it will literally look like shit (for fundamental reasons...), but if a particular amplitude bin is over-represented, that colour will dominate.

For that same reason, it ought to be completely robust against outliers.

So the dominance of blue is wrong. I can't reconcile it with the spectrum plot, where all the amplitudes are >= 10.

**Comment by o-smirnov** [comment]
Just a note that the rectangular mottling pattern is not real. #42 will probably solve it. Also, --spread-pix 3 gets rid of it nicely.

**Comment by o-smirnov** [comment]
OK, I found the problem. My fancy new aggregator wasn't ignoring flagged points properly, counting themall as part of bin 0 instead. And these calibrators are 70%+ flagged, hence the deep blue sea.

Here's a more sensible version of the same plot. The colour gradient is now representative of the spectrum, and the flagged data is missing as it ought to be.

![image](https://user-images.githubusercontent.com/6470079/80377447-989dac80-889b-11ea-965d-0bcc1895a346.png)
