### ISSUE TITLE
make PyPI release

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/shadeMS#91]
0.5.0 is ready for PyPI I think -- @Athanaseus would you do the necessary please?

**Comment by Athanaseus** [comment]
I just added a workflow to publish the package on every tag we push.

Since we already have a tag on github, we need to push this to pypi manually using twine:
`git checkout v0.5.0`                               # checkout the tag
`pip install twine`                                    # install twine if not already done so
`python setup.py sdist bdist_wheel`      # create distribution files
`twine upload -r testpypi dist/*`              # upload to testpypi (not really necessary but for testing deployment)
`twine upload dist/*`                               # now upload to pypi (this will need pypi `usr` & `pswd`)

This I can do i think. After this is done we need to generate a token, that should be added to github secret (this needs admin rights). Then all will be good.

**Comment by Athanaseus** [comment]
I pushed 0.5.0 using twine. To test automatic deployment we need to set up secret keys. I can get them on pypi but I do not have admin rights to add them on shadems github.

NB: To make a 0.5.1 release we also have to bump the version in [setup.py#L21](https://github.com/ratt-ru/shadeMS/blob/master/setup.py#L21)

**Comment by o-smirnov** [comment]
OK let's forget 0.5.1 for now, I was only doing it to test the workflow. Which I think all works, except you need to add osmirnov to the shadems project on PyPI.

**Comment by Athanaseus** [comment]
Cool, Invitation sent.

**Comment by o-smirnov** [comment]
Thanks -- done. I've added my PyPI token to secrets, so the next release should go up automatically. I've deleted 0.5.1 for now.

**Comment by o-smirnov** [comment]
Oh, could you please add PyPI badges to the README?
